# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.3
notifications:
  email: false
matrix:
  allow_failures:
    - os: osx
# uncomment the following lines to override the default test script
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'versioninfo()'
#   - julia --color=yes -e 'Pkg.clone(pwd())'
#   - julia --color=yes -e 'Pkg.add("ApproxFun"); Pkg.checkout("ApproxFun","development"); using ApproxFun'
#   - julia --color=yes -e 'Pkg.build("Poltergeist"); Pkg.test("Poltergeist"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Poltergeist")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  #- julia -e 'cd(Pkg.dir("Poltergeist")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
